### ISSUE TITLE
3.0 roadmap

### ISSUE THREAD

**Issue by rtsao** [rtsao/unitest#34]
Replacing Electron with headless Chrome laid down a lot of the groundwork to a fully Chrome DevTools Protocol based solution.

- [ ] Restructure into monorepo https://github.com/rtsao/unitest/issues/16
- [ ] New, standalone assertion library https://github.com/rtsao/unitest/issues/32
- [ ] Migrate the Node.js runner to use CDP https://github.com/rtsao/unitest/issues/24
- [ ] Multicore parallel testing and glob support
